#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_ENV="${1:-${APP_STACK_ENV:-}}"
if [[ $# -gt 1 ]]; then
  echo "Usage: $0 [public|prod|<env-name>]" >&2
  exit 1
fi

if [[ -z "$TARGET_ENV" ]]; then
  echo "Set the target environment explicitly: $0 [public|prod|<env-name>]" >&2
  echo "You may also export APP_STACK_ENV, but deploys should not rely on implicit defaults." >&2
  exit 1
fi

ENV_DIR="$ROOT_DIR/env/$TARGET_ENV"
COMPOSE_FILE="$ROOT_DIR/compose.yml"
COMPOSE_ENV="$ENV_DIR/compose.env"
BACKEND_ENV="$ENV_DIR/backend.env"
DB_ENV="$ENV_DIR/db.env"
NGINX_TEMPLATE="$ROOT_DIR/nginx/default.conf.template"
NGINX_RENDER_DIR="$ENV_DIR/nginx"
NGINX_RENDERED_CONF="$NGINX_RENDER_DIR/default.conf"
APP_ROLE_SCRIPT="$ROOT_DIR/postgres/create-app-role.sh"
DURABILITY_DIR="${DURABILITY_DIR:-$ROOT_DIR/../../../durability/backend}"
BACKUP_SCRIPT="$DURABILITY_DIR/backup-db.sh"

if [[ ! -d "$ENV_DIR" ]]; then
  echo "Missing environment directory: $ENV_DIR" >&2
  echo "Create host-local runtime files there, for example from env/$TARGET_ENV/*.example." >&2
  exit 1
fi

for required_file in "$COMPOSE_ENV" "$BACKEND_ENV" "$DB_ENV" "$NGINX_TEMPLATE"; do
  if [[ ! -f "$required_file" ]]; then
    echo "Missing required file: $required_file" >&2
    exit 1
  fi
done

set -a
# shellcheck disable=SC1090
source "$COMPOSE_ENV"
set +a

for required_compose_var in COMPOSE_PROJECT_NAME APP_STACK_ENV_DIR POSTGRES_VOLUME_NAME NGINX_BIND_PORT BACKEND_SHARED_NETWORK; do
  if [[ -z "${!required_compose_var:-}" ]]; then
    echo "Set $required_compose_var in compose.env." >&2
    exit 1
  fi
done

for required_host_file_var in FIREBASE_ADMIN_CREDENTIALS_PATH AWS_SHARED_CREDENTIALS_PATH; do
  required_host_file="${!required_host_file_var:-}"
  if [[ -z "$required_host_file" ]]; then
    echo "Set $required_host_file_var in compose.env." >&2
    exit 1
  fi

  if [[ ! -f "$required_host_file" ]]; then
    echo "Missing required host file from $required_host_file_var: $required_host_file" >&2
    exit 1
  fi
done

for required_executable in "$APP_ROLE_SCRIPT" "$BACKUP_SCRIPT"; do
  if [[ ! -x "$required_executable" ]]; then
    echo "Missing executable script: $required_executable" >&2
    exit 1
  fi
done

if ! docker network inspect "$BACKEND_SHARED_NETWORK" >/dev/null 2>&1; then
  echo "Missing Docker network: $BACKEND_SHARED_NETWORK" >&2
  echo "Create it before deploy: docker network create $BACKEND_SHARED_NETWORK" >&2
  exit 1
fi

mkdir -p "$NGINX_RENDER_DIR"
BACKEND_UPSTREAM_HOST="${COMPOSE_PROJECT_NAME}-backend:8000"
python3 - "$NGINX_TEMPLATE" "$NGINX_RENDERED_CONF" "$BACKEND_UPSTREAM_HOST" <<'PY'
from pathlib import Path
import sys

template_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
backend_upstream_host = sys.argv[3]
text = template_path.read_text()
text = text.replace("${BACKEND_UPSTREAM_HOST}", backend_upstream_host)
header = "# This file is generated by ops/deployment/backend/app-stack/deploy.sh.\n# Do not edit this file directly; update nginx/default.conf.template instead.\n\n"
output_path.write_text(header + text)
PY

compose() {
  docker compose --env-file "$COMPOSE_ENV" -f "$COMPOSE_FILE" "$@"
}

echo "Pulling runtime images..."
compose pull nginx backend worker db

echo "Ensuring database is running before backup and migration..."
compose up -d db

echo "Ensuring backend app database role exists..."
APP_STACK_ENV="$TARGET_ENV" "$APP_ROLE_SCRIPT"

echo "Creating pre-deploy backup..."
APP_STACK_ENV="$TARGET_ENV" "$BACKUP_SCRIPT"

echo "Running Alembic migrations..."
compose run --rm backend alembic upgrade head

echo "Reconciling Plaid item webhook URLs..."
compose run --rm backend python -m src.plaid_webhook_reconciler --apply

echo "Updating runtime services..."
compose up -d nginx backend worker

echo "Waiting for service health..."
compose up -d --wait nginx backend worker

echo "Verifying readiness endpoint through nginx..."
curl --fail --silent "http://127.0.0.1:${NGINX_BIND_PORT}/health/ready" >/dev/null

echo "Deploy complete."
