/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/plaid/create_link_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Link Token */
        post: operations["create_link_token_api_v1_plaid_create_link_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plaid/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Item
         * @description Exchange a Plaid public_token for a persistent access_token.
         *     The access_token is envelope-encrypted with KMS (AES-256-GCM) and
         *     stored in the plaid_items table alongside the KMS-encrypted data key.
         */
        post: operations["add_item_api_v1_plaid_item_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plaid/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Items
         * @description Return all Plaid items belonging to the authenticated user.
         *
         *     NOTE: Access tokens are returned as raw encrypted bytes — they are NOT
         *     decrypted here.  Callers should treat these fields as opaque.
         *
         *     TODO: Replace raw row serialisation with a proper response DTO/schema
         *           (e.g. a Pydantic model) that explicitly controls which fields are
         *           exposed.  At minimum, omit the ciphertext fields from the public
         *           response once decryption is wired up.
         *     TODO: Decrypt access_token_ciphertext via KMS before using the token for
         *           any downstream Plaid API calls (see services/aws/kms.py).
         *     TODO: Add pagination (skip / limit) if a user can have many linked items.
         */
        get: operations["get_items_api_v1_plaid_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plaid/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Accounts
         * @description Return all accounts for the authenticated user, grouped by linked item
         *     (institution).  Each item carries its institution name so the client
         *     can render a grouped list without a second request.
         *
         *     Only active accounts (is_active=True) are returned.  Hidden accounts
         *     (is_hidden=True) are included so the client can render a 'hidden'
         *     section — filter them out client-side if not needed.
         */
        get: operations["get_accounts_api_v1_plaid_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Or Create Me */
        post: operations["get_or_create_me_api_v1_users_me_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountDTO
         * @description A single bank account within a linked item, with only the fields the
         *     client needs to display it.  Sensitive / internal fields are omitted.
         */
        AccountDTO: {
            /**
             * Id
             * Format: uuid
             * @description Internal app UUID for this account.
             */
            id: string;
            /**
             * Plaid Account Id
             * @description Plaid's own account identifier.
             */
            plaid_account_id: string;
            /**
             * Mask
             * @description Last 2-4 digits of the account number.
             */
            mask?: string | null;
            /**
             * Name
             * @description Account name assigned by the user or institution.
             */
            name: string;
            /**
             * Official Name
             * @description Official account name given by the institution.
             */
            official_name?: string | null;
            /**
             * Account Type
             * @description Top-level type: depository, credit, loan, investment, other.
             */
            account_type?: string | null;
            /**
             * Account Subtype
             * @description Subtype: checking, savings, credit card, etc.
             */
            account_subtype?: string | null;
            /**
             * Is Active
             * @description Whether the account is active.
             */
            is_active: boolean;
            /**
             * Is Hidden
             * @description Whether the account has been hidden by the user.
             */
            is_hidden: boolean;
            /**
             * Display Order
             * @description User-defined display ordering.
             */
            display_order?: number | null;
        };
        /**
         * AddItemResponseDTO
         * @description Confirmation returned after a public token is successfully exchanged.
         */
        AddItemResponseDTO: {
            /**
             * Item Id
             * @description Plaid item_id for the newly linked institution.
             */
            item_id: string;
            /**
             * Status
             * @description Always 'ok' on success.
             * @default ok
             */
            status: string;
        };
        /** Body_add_item_api_v1_plaid_item_post */
        Body_add_item_api_v1_plaid_item_post: {
            /** Public Token */
            public_token: string;
        };
        /**
         * CreateLinkTokenResponseDTO
         * @description Plaid link token returned to the frontend to initialise Plaid Link.
         */
        CreateLinkTokenResponseDTO: {
            /**
             * Link Token
             * @description Opaque token passed to Plaid Link on the client.
             */
            link_token: string;
            /**
             * Expiration
             * Format: date-time
             * @description Expiry timestamp for the link token.
             */
            expiration: string;
            /**
             * Request Id
             * @description Plaid request ID for debugging.
             */
            request_id: string;
        };
        /**
         * GetAccountsResponseDTO
         * @description All items with their accounts for the authenticated user.
         */
        GetAccountsResponseDTO: {
            /** Items */
            items: components["schemas"]["ItemWithAccountsDTO"][];
        };
        /**
         * GetItemsResponseDTO
         * @description Wrapper around the list of linked Plaid items.
         */
        GetItemsResponseDTO: {
            /** Items */
            items: components["schemas"]["PlaidItemDTO"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemWithAccountsDTO
         * @description A linked item (institution connection) together with all its accounts.
         *     This is the primary shape the client uses to render the accounts list.
         */
        ItemWithAccountsDTO: {
            /**
             * Item Id
             * Format: uuid
             * @description Internal app UUID for this item.
             */
            item_id: string;
            /**
             * Plaid Item Id
             * @description Plaid's own item identifier.
             */
            plaid_item_id: string;
            /**
             * Institution Id
             * @description Plaid institution_id.
             */
            institution_id?: string | null;
            /**
             * Institution Name
             * @description Human-readable institution name, e.g. 'Chase'.
             */
            institution_name?: string | null;
            /**
             * Status
             * @description Item status: active | revoked | error.
             */
            status: string;
            /**
             * Accounts
             * @description Accounts belonging to this item, ordered by display_order then name.
             */
            accounts?: components["schemas"]["AccountDTO"][];
        };
        /**
         * PlaidItemDTO
         * @description A single linked Plaid item (institution connection) belonging to the user.
         *
         *     Encrypted credential fields are intentionally omitted from this DTO.
         *     TODO: Remove access_token_* fields below once decryption + a dedicated
         *           'fetch transactions' endpoint is implemented — they should never
         *           be sent over the wire in production.
         */
        PlaidItemDTO: {
            /**
             * Id
             * Format: uuid
             * @description Internal app UUID for this Plaid item.
             */
            id: string;
            /**
             * Plaid Item Id
             * @description Plaid's own item identifier.
             */
            plaid_item_id: string;
            /**
             * Institution Id
             * @description Plaid institution_id, if available.
             */
            institution_id?: string | null;
            /**
             * Institution Name
             * @description Human-readable institution name (e.g. 'Chase'), resolved at link time.
             */
            institution_name?: string | null;
            /**
             * Status
             * @description Item status: active | revoked | error.
             */
            status: string;
            /**
             * Kms Key Id
             * @description KMS CMK used to encrypt the access token.
             */
            kms_key_id?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description When this item was first linked.
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description When this item was last modified.
             */
            updated_at: string;
            /**
             * Access Token Ciphertext
             * @description [TEMP] Hex-encoded AES-GCM ciphertext of the Plaid access token.
             */
            access_token_ciphertext: string;
            /**
             * Access Token Nonce
             * @description [TEMP] Hex-encoded AES-GCM nonce used when encrypting the access token.
             */
            access_token_nonce: string;
            /**
             * Access Token Encrypted Data Key
             * @description [TEMP] Hex-encoded KMS-encrypted data key (CiphertextBlob).
             */
            access_token_encrypted_data_key: string;
        };
        /** UserResponseDTO */
        UserResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Firebase Uid */
            firebase_uid: string;
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_link_token_api_v1_plaid_create_link_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLinkTokenResponseDTO"];
                };
            };
        };
    };
    add_item_api_v1_plaid_item_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_add_item_api_v1_plaid_item_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddItemResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_items_api_v1_plaid_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetItemsResponseDTO"];
                };
            };
        };
    };
    get_accounts_api_v1_plaid_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAccountsResponseDTO"];
                };
            };
        };
    };
    get_or_create_me_api_v1_users_me_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
}
