/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/plaid/create_link_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Link Token */
        post: operations["create_link_token_api_v1_plaid_create_link_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plaid/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_v1_plaid_item_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plaid/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Household Connections */
        get: operations["get_household_connections_api_v1_plaid_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plaid/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Household Accounts */
        get: operations["get_household_accounts_api_v1_plaid_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plaid/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Plaid Webhook */
        post: operations["receive_plaid_webhook_api_v1_plaid_webhooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Or Create Me */
        post: operations["get_or_create_me_api_v1_users_me_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Household */
        post: operations["create_household_api_v1_households_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/me/household": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Household */
        get: operations["get_my_household_api_v1_households_me_household_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/me/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Membership */
        get: operations["get_my_membership_api_v1_households_me_membership_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{household_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Household */
        post: operations["join_household_api_v1_households__household_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{household_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Household Members */
        get: operations["get_household_members_api_v1_households__household_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/{household_id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave Household */
        delete: operations["leave_household_api_v1_households__household_id__leave_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/named-queries/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Named Query */
        post: operations["preview_named_query_api_v1_named_queries_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/named-queries/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Named Query */
        post: operations["generate_named_query_api_v1_named_queries_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/named-queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Named Queries */
        get: operations["list_named_queries_api_v1_named_queries_get"];
        put?: never;
        /** Create Named Query */
        post: operations["create_named_query_api_v1_named_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/named-queries/{named_query_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Named Query Data */
        get: operations["get_named_query_data_api_v1_named_queries__named_query_id__data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/named-queries/{named_query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Named Query */
        delete: operations["delete_named_query_api_v1_named_queries__named_query_id__delete"];
        options?: never;
        head?: never;
        /** Patch Named Query */
        patch: operations["patch_named_query_api_v1_named_queries__named_query_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountSimpleDTO
         * @description A single Account with only the fields the client needs to display it.
         */
        AccountSimpleDTO: {
            /**
             * Id
             * Format: uuid
             * @description Internal app UUID for this account.
             */
            id: string;
            /**
             * Mask
             * @description Last 2-4 digits of the account number.
             */
            mask?: string | null;
            /**
             * Name
             * @description Account name assigned by the user or institution.
             */
            name: string;
            /**
             * Official Name
             * @description Official account name given by the institution.
             */
            official_name?: string | null;
            /**
             * Account Type
             * @description Top-level type: depository, credit, loan, investment, other.
             */
            account_type?: string | null;
            /**
             * Account Subtype
             * @description Subtype: checking, savings, credit card, etc.
             */
            account_subtype?: string | null;
            /**
             * Is Active
             * @description Whether the account is active.
             */
            is_active: boolean;
            /**
             * Is Hidden
             * @description Whether the account has been hidden by the user.
             */
            is_hidden: boolean;
            /**
             * Display Order
             * @description User-defined display ordering.
             */
            display_order?: number | null;
        };
        /** Body_add_item_api_v1_plaid_item_post */
        Body_add_item_api_v1_plaid_item_post: {
            /** Link Public Token */
            link_public_token: string;
        };
        /** ColumnMeta */
        ColumnMeta: {
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /**
         * ConnectionWithAccountsDTO
         * @description An InstitutionConnection together with all its Accounts.
         */
        ConnectionWithAccountsDTO: {
            /**
             * Connection Id
             * Format: uuid
             * @description Internal app UUID for this connection.
             */
            connection_id: string;
            /**
             * Institution Name
             * @description Human-readable institution name, e.g. 'Chase'.
             */
            institution_name?: string | null;
            /**
             * Status
             * @description Connection status: active | revoked | member_departed.
             */
            status: string;
            /**
             * Accounts
             * @description Accounts belonging to this connection, ordered by display_order then name.
             */
            accounts?: components["schemas"]["AccountSimpleDTO"][];
        };
        /** CreateHouseholdRequest */
        CreateHouseholdRequest: {
            /** Name */
            name: string;
        };
        /**
         * CreateLinkTokenResponseDTO
         * @description Plaid link token returned to the frontend to initialise Plaid Link.
         */
        CreateLinkTokenResponseDTO: {
            /**
             * Link Token
             * @description Opaque token passed to Plaid Link on the client.
             */
            link_token: string;
            /**
             * Expiration
             * Format: date-time
             * @description Expiry timestamp for the link token.
             */
            expiration: string;
            /**
             * Request Id
             * @description Plaid request ID for debugging.
             */
            request_id: string;
        };
        /**
         * GetAccountsResponseDTO
         * @description All InstitutionConnections with their Accounts for the authenticated user.
         */
        GetAccountsResponseDTO: {
            /** Items */
            items: components["schemas"]["ConnectionWithAccountsDTO"][];
        };
        /**
         * GetConnectionsResponseDTO
         * @description Wrapper around the list of linked institution connections.
         */
        GetConnectionsResponseDTO: {
            /** Items */
            items: components["schemas"]["InstitutionConnectionSimpleDTO"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HouseholdResponse */
        HouseholdResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * InstitutionConnectionSimpleDTO
         * @description A single linked institution connection belonging to the user.
         */
        InstitutionConnectionSimpleDTO: {
            /**
             * Id
             * Format: uuid
             * @description Internal app UUID for this connection.
             */
            id: string;
            /**
             * Institution Name
             * @description Human-readable institution name (e.g. 'Chase'), resolved at link time.
             */
            institution_name?: string | null;
            /**
             * Status
             * @description Connection status: active | revoked | member_departed.
             */
            status: string;
            /**
             * Created At
             * Format: date-time
             * @description When this connection was first linked.
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description When this connection was last modified.
             */
            updated_at: string;
        };
        /** MembershipResponse */
        MembershipResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Household Id
             * Format: uuid
             */
            household_id: string;
            /** Role */
            role: string;
        };
        /** NamedQueryCreateRequest */
        NamedQueryCreateRequest: {
            /**
             * Name
             * @description Human-readable label for this Named Query
             */
            name: string;
            /**
             * Sql Query
             * @description Flat SELECT against widget_transactions or widget_accounts
             */
            sql_query: string;
            /**
             * Chart Type
             * @description Opaque chart type hint for the frontend
             */
            chart_type?: string | null;
        };
        /** NamedQueryCandidate */
        NamedQueryCandidate: {
            /** Sql Query */
            sql_query: string;
            /** Chart Type */
            chart_type?: string | null;
        };
        /** NamedQueryCandidateResponse */
        NamedQueryCandidateResponse: {
            /** Type */
            type?: "named_query_candidate";
            /** Name */
            name: string;
            candidate: components["schemas"]["NamedQueryCandidate"];
        };
        /** NamedQueryClarifyingQuestionResponse */
        NamedQueryClarifyingQuestionResponse: {
            /** Type */
            type?: "clarifying_question";
            /** Question */
            question: string;
        };
        /** NamedQueryDataResponse */
        NamedQueryDataResponse: {
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Truncated */
            truncated: boolean;
        };
        /** NamedQueryGenerateRequest */
        NamedQueryGenerateRequest: {
            /** Messages */
            messages: components["schemas"]["NamedQueryGenerationMessage"][];
        };
        /** NamedQueryGenerationFailureResponse */
        NamedQueryGenerationFailureResponse: {
            /** Type */
            type?: "generation_failure";
            /** Message */
            message: string;
        };
        /** NamedQueryGenerationMessage */
        NamedQueryGenerationMessage: {
            /** Role */
            role: "member" | "assistant";
            /** Content */
            content: string;
        };
        /** NamedQueryPatchRequest */
        NamedQueryPatchRequest: {
            /** Name */
            name?: string | null;
            /** Sql Query */
            sql_query?: string | null;
            /** Chart Type */
            chart_type?: string | null;
        };
        /** NamedQueryPreviewRequest */
        NamedQueryPreviewRequest: {
            /**
             * Sql Query
             * @description Flat SELECT to preview without saving
             */
            sql_query: string;
        };
        /** NamedQueryResponse */
        NamedQueryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Household Id
             * Format: uuid
             */
            household_id: string;
            /** Name */
            name: string;
            /** Sql Query */
            sql_query: string;
            /** Referenced Columns */
            referenced_columns: string[] | null;
            /** Chart Type */
            chart_type: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserResponseDTO */
        UserResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Firebase Uid */
            firebase_uid: string;
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_link_token_api_v1_plaid_create_link_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLinkTokenResponseDTO"];
                };
            };
        };
    };
    add_item_api_v1_plaid_item_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_add_item_api_v1_plaid_item_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_household_connections_api_v1_plaid_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetConnectionsResponseDTO"];
                };
            };
        };
    };
    get_household_accounts_api_v1_plaid_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAccountsResponseDTO"];
                };
            };
        };
    };
    receive_plaid_webhook_api_v1_plaid_webhooks_post: {
        parameters: {
            query?: never;
            header?: {
                "Plaid-Verification"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_or_create_me_api_v1_users_me_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    create_household_api_v1_households_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHouseholdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_household_api_v1_households_me_household_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdResponse"];
                };
            };
        };
    };
    get_my_membership_api_v1_households_me_membership_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
        };
    };
    join_household_api_v1_households__household_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_household_members_api_v1_households__household_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_household_api_v1_households__household_id__leave_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_named_query_api_v1_named_queries_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedQueryGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json":
                        | components["schemas"]["NamedQueryClarifyingQuestionResponse"]
                        | components["schemas"]["NamedQueryCandidateResponse"]
                        | components["schemas"]["NamedQueryGenerationFailureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_named_query_api_v1_named_queries_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedQueryPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_named_queries_api_v1_named_queries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryResponse"][];
                };
            };
        };
    };
    create_named_query_api_v1_named_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedQueryCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_named_query_data_api_v1_named_queries__named_query_id__data_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                named_query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_named_query_api_v1_named_queries__named_query_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                named_query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_named_query_api_v1_named_queries__named_query_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                named_query_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamedQueryPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
